//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogiUzytkownikow
    {
        public int IdLogi { get; set; }
        public int Uzytkownik { get; set; }
        public string Opis { get; set; }
        public string Komputer { get; set; }
        public System.DateTime DataCzasLogu { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
