//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZdarzeniaEntities : DbContext
    {
        public ZdarzeniaEntities()
            : base("name=ZdarzeniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Obiekty> Obiekty { get; set; }
        public virtual DbSet<TypyZdarzen> TypyZdarzen { get; set; }
        public virtual DbSet<Zdarzenia> Zdarzenia { get; set; }
        public virtual DbSet<ViewObiekty> ViewObiekty { get; set; }
        public virtual DbSet<Zalaczniki> Zalaczniki { get; set; }
        public virtual DbSet<LogiUzytkownikow> LogiUzytkownikow { get; set; }
        public virtual DbSet<StatusZdarzenia> StatusZdarzenia { get; set; }
        public virtual DbSet<ViewZdarzenieFull> ViewZdarzenieFull { get; set; }
        public virtual DbSet<ViewZdarzeniaLista> ViewZdarzeniaLista { get; set; }
    }
}
