//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Zdarzenia = new HashSet<Zdarzenia>();
            this.LogiUzytkownikow = new HashSet<LogiUzytkownikow>();
        }
    
        public int Id { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public System.DateTime DataDodania { get; set; }
        public System.DateTime DataKoniec { get; set; }
        public bool CzyAdministrator { get; set; }
        public bool CzyKierownik { get; set; }
        public bool CzyZablokowany { get; set; }
        public bool CzyNoweHaslo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdarzenia> Zdarzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogiUzytkownikow> LogiUzytkownikow { get; set; }
    }
}
