//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewZdarzenieFull
    {
        public int IdZdarzenia { get; set; }
        public int NrZdarzenia { get; set; }
        public string Nazwa { get; set; }
        public string Uzytkownik { get; set; }
        public string NazwaObiektu { get; set; }
        public int IdUser { get; set; }
        public int IdObiekt { get; set; }
        public System.DateTime DataZdarzenia { get; set; }
        public string NazwaStatus { get; set; }
        public string NazwaTyp { get; set; }
        public int IdTypZdarzenia { get; set; }
        public int IdStatus { get; set; }
        public string OpisObiektu { get; set; }
        public string OpisZdarzenia { get; set; }
        public string Dzialania { get; set; }
        public int IdUzytkownik { get; set; }
        public string UwagiDoZdarzenia { get; set; }
        public string OpisStatus { get; set; }
        public string OpisTyp { get; set; }
        public string login { get; set; }
    }
}
