//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewObiekty
    {
        public int IdObiekt { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public bool CzyZablokowany { get; set; }
    }
}
