//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaportZdarzen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdarzenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zdarzenia()
        {
            this.Zalaczniki = new HashSet<Zalaczniki>();
        }
    
        public int IdZdarzenia { get; set; }
        public int NrZdarzenia { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string Dzialania { get; set; }
        public int Uzytkownik { get; set; }
        public int Obiekt { get; set; }
        public int TypZdarz { get; set; }
        public System.DateTime DataZdarzenia { get; set; }
        public string UwagiDoZdarzenia { get; set; }
        public int Status { get; set; }
    
        public virtual Obiekty Obiekty { get; set; }
        public virtual Users Users { get; set; }
        public virtual TypyZdarzen TypyZdarzen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zalaczniki> Zalaczniki { get; set; }
        public virtual StatusZdarzenia StatusZdarzenia { get; set; }
    }
}
